### ISSUE TITLE
I seem to be unable to scale a VPC down

### ISSUE THREAD

**Issue by konstantint** [waldur/waldur-homeport#2]
I'd like to scale [this VPC](https://minu.etais.ee/#/resources/OpenStack.Tenant/b3d10cdd34064ad6b5fa8580e74ccb72/) down to a "trial package" and I'm not sure why I am unable to do so.

**Comment by AmbientLighter** [comment]
@konstantint To change the package select Change VPC package on the Actions dropdown. You will be presented with a list of available VPC packages. Select the one you need and click Submit button
See also [user guide](https://opennode.atlassian.net/wiki/spaces/WD/pages/22978637/OpenStack+Tenant+management).

Please note, that this action could be disabled, if you don't have enough permissions, or quota usage is over limit for new package. Could you please provide more details? Is this action disabled or is there any error messages?

**Comment by konstantint** [comment]
I know that, but I do not see the Trial package in the list of choices, although previously I did.
The only thing that changed is that I added a new machine, used it for some time, and then removed.

**Comment by konstantint** [comment]
Oh wait, now I see it. I guess then the issue had something to do with caching or synchronization.

**Comment by AmbientLighter** [comment]
@konstantint Please note that this commit improves VPC change dialog. Previously, it has been hiding  options that are not fitting VPC usage. Now it always shows available options, but disables them from selection with a tooltip.

https://github.com/opennode/waldur-homeport/commit/6f792cbf4cf6ebdfe91629b66481c59f25c259cc

![vpc-change](https://user-images.githubusercontent.com/228225/35407326-a4ab05d4-021c-11e8-9cf8-8efb2b8199b1.png)

Therefore I'm closing this issue.
