### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by ictinc** [waldur/waldur-homeport#3]
Hi there, 
For my startup cloud hosting business I came across Waldur. 
I've installed it on my server following the documentation:
https://opennode.atlassian.net/wiki/spaces/WD/pages/22980728/Deployment
Although I'm able to get to the administration login I'm not sure what the default login/password would be. 
Do I somehow need to specify this in the config or is there a default I can use?

**Comment by AmbientLighter** [comment]
Hi, @ictinc 

There's no default login/password, therefore you should create first staff user via Waldur CLI:

```
su - waldur -c "waldur createstaffuser -u staff -p staffSecretPasswordChangeMe"
```

Thank you for the question and note that deployment guide has been updated to include this step as well.
