### ISSUE TITLE
How to enable disabledfeatures in waldur

### ISSUE THREAD

**Issue by monishmonish** [waldur/waldur-homeport#55]
Hi,

I have an doubt,  Kindly, tell me how to enable the disabledfeatures in waldur homeport configuration.

**Comment by KubeCirrus** [comment]
Try enabling the features in support -->features.

**Comment by monishmonish** [comment]
Yes Bcouddot,

Im already enabled the features in support --> features. but, it fails.

I exactly need these features.

![image](https://user-images.githubusercontent.com/103207396/162426972-0d20bfe3-b150-407b-8aa6-0d1e1eb0eebd.png)
