### ISSUE TITLE
no such file or directory ERROR for /app/build-info 

### ISSUE THREAD

**Issue by tyagisanjeev1211** [waldur/waldur-homeport#70]
In Dockerfile, On line 20, there is COPY instruction mentioned as: 
`COPY --from=build /app/build-info/ /build-info/`

this line is producing error mentioned as below: 
`Error: building at STEP "COPY --from=build /app/build-info/ /build-info/": checking on sources under "/home/<user>/.local/share/containers/storage/overlay/859a6109441e09d4ba79f63ed1d69a498652dff8b0db0f1ca86f69f50ca24c4a/merged": copier: stat: "/app/build-info": no such file or directory
`

**Comment by livenson** [comment]
This is very strange, I suspect something breaks in your system when you are builing it.

Can you provide the full log please?

ps https://github.com/waldur/waldur-homeport/blob/develop/.gitlab-ci.yml#L178 - as you can see, we build Dockerfile many times per day.

**Comment by tyagisanjeev1211** [comment]
_Please find console logs a below:_ 

`[1/2] STEP 1/10: FROM node:lts-alpine AS build
[1/2] STEP 2/10: WORKDIR /app
--> e69002c270ae
[1/2] STEP 3/10: ENV PATH /app/node_modules/.bin:$PATH
--> 8f531d4ea311
[1/2] STEP 4/10: COPY package.json yarn.lock /app/
--> 9bdce726d1dd
[1/2] STEP 5/10: RUN apk add --no-cache git && yarn install --frozen-lockfile
fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/x86_64/APKINDEX.tar.gz
(1/13) Installing ca-certificates (20240705-r0)
(2/13) Installing brotli-libs (1.1.0-r2)
(3/13) Installing c-ares (1.33.1-r0)
(4/13) Installing libunistring (1.2-r0)
(5/13) Installing libidn2 (2.3.7-r0)
(6/13) Installing nghttp2-libs (1.62.1-r0)
(7/13) Installing libpsl (0.21.5-r1)
(8/13) Installing zstd-libs (1.5.6-r0)
(9/13) Installing libcurl (8.10.1-r0)
(10/13) Installing libexpat (2.6.3-r0)
(11/13) Installing pcre2 (10.43-r0)
(12/13) Installing git (2.45.2-r0)
(13/13) Installing git-init-template (2.45.2-r0)
Executing busybox-1.36.1-r29.trigger
Executing ca-certificates-20240705-r0.trigger
OK: 23 MiB in 29 packages
yarn install v1.22.22
[1/4] Resolving packages...
[2/4] Fetching packages...
warning smol-toml@1.1.4: The engine "pnpm" appears to be invalid.
[3/4] Linking dependencies...
warning " > draft-js@0.11.4" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-rc || ^16.0.0-rc || ^16.0.0".
warning " > draft-js@0.11.4" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0-rc || ^16.0.0-rc || ^16.0.0".
warning " > react-custom-scrollbars@4.2.1" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning " > react-custom-scrollbars@4.2.1" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
warning " > react-draft-wysiwyg@1.14.7" has incorrect peer dependency "react@0.13.x || 0.14.x || ^15.0.0-0 || 15.x.x || ^16.0.0-0 || ^16.x.x || ^17.x.x".
warning " > react-draft-wysiwyg@1.14.7" has incorrect peer dependency "react-dom@0.13.x || 0.14.x || ^15.0.0-0 || 15.x.x || ^16.0.0-0 || ^16.x.x || ^17.x.x".
[4/4] Building fresh packages...
$ husky
.git can't be foundDone in 69.90s.
--> b7481d631284
[1/2] STEP 6/10: COPY . /app
--> 0c15d9d5053c
[1/2] STEP 7/10: ARG VERSION=latest
--> b91b1cf35896
[1/2] STEP 8/10: ARG ASSET_PATH="/"
--> 74a03220807d
[1/2] STEP 9/10: RUN sed -i "s/buildId: 'develop'/buildId: '$VERSION'/" src/configs/default.ts
--> 36a48d740a4d
[1/2] STEP 10/10: RUN echo $ASSET_PATH && yarn build
/
yarn run v1.22.22
$ cross-env NODE_ENV=production webpack --config=webpack.config.prod.js
1234 assets
11470 modules

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  json.worker.js (360 KiB)
  c1e38fd9e0e74ba58f7a.svg?v=4.7.0 (434 KiB)
  images/estonian-bog.jpg?addcc139a466cade4b56 (541 KiB)
  scripts/36727.js?c03accb51abcc11567e9 (1.21 MiB)
  scripts/81493.js?60b51757aaf5a5a4d31f (2.9 MiB)
  scripts/70596.js?49843808ae5292c7bf93 (821 KiB)
  scripts/94061.js?2f1bbdfc08e4711cd30f (496 KiB)
  css/dark-bundle.css?ddc299fd54a61a90ae79 (1.39 MiB)
  css/light-bundle.css?c71359ab260f37e9cb5f (1.39 MiB)
  scripts/index.bundle.js?048240b4212928309688 (1.4 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  index (1.45 MiB)
      css/index-bundle.css?a0e310775b9f1620a112
      scripts/index.bundle.js?048240b4212928309688

webpack 5.61.0 compiled with 2 warnings in 157822 ms
Done in 181.60s.
--> fec8035d48bb
[2/2] STEP 1/11: FROM nginx:stable-alpine
[2/2] STEP 2/11: COPY --from=build /app/build /usr/share/nginx/html
--> ee1179044728
[2/2] STEP 3/11: COPY --from=build /app/build/index.html /usr/share/nginx/html/index.orig.html
--> d93c461eb049
[2/2] STEP 4/11: COPY --from=build /app/build-info/ /build-info/
Error: building at STEP "COPY --from=build /app/build-info/ /build-info/": checking on sources under "/home/sanjeev/.local/share/containers/storage/overlay/d6734db3b27c80d18cd42889e0849d9af87c031e3b382689c26a5e891aa1c4fa/merged": copier: stat: "/app/build-info": no such file or directory
`

**Comment by livenson** [comment]
Thanks, can you please share also build environment details? OS and tool.

**Comment by tyagisanjeev1211** [comment]
```
NAME="Rocky Linux"
VERSION="8.10 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.10 (Green Obsidian)"

```

for Build, I am using Podman 

`podman build -t waldur-homeport .
`

**Comment by bugblasterX** [comment]
Hello @tyagisanjeev1211 ,
while we will patch the Dockerfile, could you try this workaround and see if it works for now?
`RUN mkdir -p /app/build-info && echo "local-build" > /app/build-info/COMMIT_SHA`

Add this to your Dockerfile, under the `COPY . /app` line.
