### ISSUE TITLE
Error on adding public offering

### ISSUE THREAD

**Issue by rohitbatham** [waldur/waldur-homeport#9]
Hi @AmbientLighter , @mikeyakymenko, @RonBalnen,

You guys are really doing an amazing job! using great tech stack and this tool has lots of features. I recently installed it on my machine.

but I don't know I am asking the right question or not even I might be wrong as i have least insight about the application workflow. Still seeking your help here.

### **Problem** 

After creating organization, I am adding public offering but it throws an error. please refer the snapshot.

### **Console error** 
![image](https://user-images.githubusercontent.com/19263834/73011351-0a4c0180-3e3a-11ea-9296-ecfac5a10b76.png)

I am done with my initial analysis and then went though the debugger and I noticed its happening because **formatOfferingRequest** method is expecting an argument **component** which is empty from service. refer below snapshot

### **Server response** 
![image](https://user-images.githubusercontent.com/19263834/73011565-7af31e00-3e3a-11ea-906b-68054f5ca39d.png)

And the code is breaking on file waldur-homeport\src\marketplace\offerings\store\effects.ts line no. 68 as component is being passed null.

When i jumped inside the method which is located on waldur-homeport\src\marketplace\offerings\store\utils.ts line no. 104 method **formatOfferingRequest** so this is actually breaks on highlighted code snippet.

### **Code** 
![image](https://user-images.githubusercontent.com/19263834/73011916-403db580-3e3b-11ea-941c-8e6f161ce78e.png)

I don't know whats wrong here. Is it really mandatory to pass **component** if yes how and from where?

Looking forward for your response!

Thank you

**Comment by AmbientLighter** [comment]
Hi, @rohitbatham 

Thank you for the bug report, I will look into this issue and update you on its progress.

**Comment by AmbientLighter** [comment]
This bug has been fixed in https://github.com/opennode/waldur-homeport/commit/ca9cc82f41be600cd4bfa051b52569993816f764
